{
  "hash": "3d71f50a050930fe354658b3ca9d7013",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"MetaDocencia's workshops in numbers\"\n---\n\n::: {.cell}\n\n:::\n\n\n\n\nIn this report you will find the main characteristics of the MetaDocencia courses and workshops delivered between 2020 and 2024.\n\n\n### Workshops' total metrics\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Metrics                    |  Value|\n|:--------------------------|------:|\n|Workshops                  |    8.0|\n|# editions                 |   94.0|\n|# hours                    |  388.0|\n|# signups                  | 2404.0|\n|# attendees                | 1558.0|\n|Signups per edition        |   25.6|\n|Attendees per edition      |   16.6|\n|NPS (%)                    |   88.9|\n|Post surveys completed (%) |   79.6|\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\nOver the last 5 years, MetaDocencia has taught 94 editions and a total of 388 hours of 8 different workshops. We reached 2404 educators, researchers and technicians from 33 countries.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](cursos_files/figure-commonmark/unnamed-chunk-4-1.png)\n:::\n:::\n\n\n\n\nFrom the total signups, 64.8% attended synchronously and 79.6% completed the post workshop survey, in which we obtained an average Net Promoter Score (NPS) of 88.9% (min = 71.4, max = 100). This is considered excellent, as the NPS ranges from -100% to +100%, and values larger than +50%—our target—reflect very high satisfaction from the participants.\n\n### Metrics by workshop\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Workshops                               | # editions| # hours| # signups| # attendees| Signups per edition| Attendees per edition| NPS (%)| Post surveys completed (%)|\n|:---------------------------------------|----------:|-------:|---------:|-----------:|-------------------:|---------------------:|-------:|--------------------------:|\n|ALTa Ciencia Abierta (Open Science 101) |          4|      63|       494|         287|               123.5|                  71.8|    79.7|                       67.6|\n|How to Teach Programming Online         |          9|      27|       215|         101|                23.9|                  11.2|    92.7|                       87.3|\n|Present! Resources for Active Meetings  |         65|     195|      1434|         935|                22.1|                  14.4|    87.2|                       88.8|\n|Train the Trainer                       |          5|      80|        92|          84|                18.4|                  16.8|    88.9|                       88.9|\n|Others                                  |         11|      23|       169|         151|                15.4|                  13.7|    95.2|                       82.3|\n\n\n:::\n:::\n\n\n\n\nAmong the most popular workshops is Present! Resources for Active Meetings, which held 65 editions and drew over 1,400 participants, serving as a major gateway to the MetaDocencia community, and ALTa Ciencia Abierta—the Latin American contextualization of NASA's Open Science 101—which held the larger number of sign-ups and attendees per edition, over 100 and 70 respectively. Meanwhile, workshops like How to Teach Programming Online and Train the Trainer stand out for their high satisfaction and retention levels, marking the beginning of a learning community capable of sustaining and multiplying its impact over time.\n\n### Metrics by year\n\nSince its inception, MetaDocencia has shown consistent and strategic growth in its educational offerings, reflecting the development of a committed and collaborative learning community across Latin America.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Year| # editions| # hours| # signups| # attendees| Signups per edition| Attendees per edition| NPS (%)| Post surveys completed (%)|\n|----:|----------:|-------:|---------:|-----------:|-------------------:|---------------------:|-------:|--------------------------:|\n| 2020|         44|     143|       985|         673|                22.4|                  15.3|     NaN|                      100.0|\n| 2021|         34|     109|       602|         455|                17.7|                  13.4|    92.1|                       85.3|\n| 2022|          6|      42|       148|          80|                24.7|                  13.3|   100.0|                      100.0|\n| 2023|          6|      24|       257|         137|                42.8|                  22.8|    79.2|                       86.7|\n| 2024|          4|      70|       412|         213|               103.0|                  53.2|    83.0|                       61.0|\n\n\n:::\n:::\n\n\n\n\nIn the early years (2020–2021), the focus was on short, high-demand workshops, with a total of 78 editions in just two years. These introductory sessions—often one-day events—emerged as a rapid response to the urgent educational needs brought on by the COVID-19 pandemic, and allowed MetaDocencia to reach over 1500 participants, positioning the initiative as a key player in digital teacher training.\n\nStarting in 2022, a clear shift in strategy becomes evident. While the overall number of editions decreased, the depth and structure of the training offerings increased. MetaDocencia began to implement cohort-based programs and more extensive workshops, such as the Train the Trainer initiative and ALTa Ciencia Abierta. This transition led to a higher average workshop duration (from 3 to more than 15 hours per edition) and a growing number of participants per edition, with recent years averaging over 100 sign-ups and 50 attendees per course.\n\nIn summary, the data show a clear shift from breadth to depth: from numerous one-off introductory sessions to fewer, more intensive programs with higher engagement and learning outcomes per edition. This evolution reflects MetaDocencia’s maturing role as a community of practice, capable of delivering meaningful, sustainable, and regionally grounded educational experiences.\n",
    "supporting": [
      "cursos_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}