name: Actualizacion Evaluaciones Cohorte

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  Actualizacion-Evaluaciones-Cohorte:
    name: Actualizacion Evaluaciones Cohorte
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.TOKEN_USUARIO_JESI }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.AUTENTICACION_NO_INTERACTIVA }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install libcurl and libssl on Linux
        run: 'sudo apt-get -y install libcurl4-openssl-dev'
        shell: bash
      - name: Install CRAN packages
        run: Rscript -e 'install.packages(c("googlesheets4", "googledrive", "dplyr", "tidyr", "lubridate", "stringr))'
      - name: Run insignias R script
        run: |
          source('R/evaluaciones_cohorte.R')
        shell: Rscript {0}

