name: Recuperar registros zenodo

on:
  schedule:
    - cron: '0 20 * * 5'
  workflow_dispatch:

jobs:
  Recuperar-registros-zenodo:
    name: Recuperar registros zenodo
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.TOKEN_USUARIO_JESI }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.AUTENTICACION_NO_INTERACTIVA }}
      
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install libcurl and libssl on Linux
        run: 'sudo apt-get -y install libcurl4-openssl-dev'
        shell: bash
      - name: Install CRAN packages
        run: Rscript -e 'install.packages(c("googlesheets4", "lubridate"))'
      - name: Install libsodium 
        run: 'sudo apt-get install -y libsodium-dev'
      - name: Install librdf0-dev
        run: 'sudo apt-get install -y librdf0-dev'
      - name: Install remotes
        run: |
          Rscript -e "install.packages('remotes', repos='https://ftp.belnet.be/mirror/CRAN')"
      - name: Install zen4R
        run: |
          Rscript -e "remotes::install_github('eblondel/zen4R', dependencies = T)"
      - name: Run zenodo-dator.R script
        run: |
          source('R/zenodo-datos.R')
        shell: Rscript {0}
